project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "Challenge 1"
            file: content/01_journal/01_Challenge1.qmd
          - text: "Challenge 2"
            file: content/01_journal/02_Challenge2.qmd
          - text: "Challenge 3"
            file: content/01_journal/03_Challenge3.qmd
          - text: "Challenge 4+5"
            file: content/01_journal/04_Challenge45.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto